# **Installing NumPy library**

In [ ]:
!pip install numpy

# **Importing NumPy and giving it a short name for calling further**

In [ ]:
import numpy as np

In [ ]:
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

# **Creating a list & printing it**

In [ ]:
lst = [[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]]
lst

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

# **Checking the data type**

In [ ]:
type(lst)

list

# **Converting the list to an array using NumPy**

In [ ]:
arr = np.array(lst)

# **Again printing and checking the data type of numpy array**

In [ ]:
print(arr)
type(arr)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


numpy.ndarray

#**Dimension of the array**

In [ ]:
arr.ndim

2

#**Size of the array -> Total no of elements present inside of it**

In [ ]:
arr.size

9

#**No of elements in matrix format (row, col)**

In [ ]:
arr.shape

(3, 3)

# **dtype -> Tells which type of data the array contains**

In [ ]:
arr.dtype

dtype('int64')

#  **Creating any desired sized array with all the values predefined to 0**
## **Parameter needs to be passed -> Shape of the array (row, col)**

In [ ]:
zeros = np.zeros((3, 5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# **Can also intialize to 1**

In [ ]:
ones = np.ones((5, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# **Generate a random no using numpy (always gives a value b/w 0 and 1)**

In [ ]:
np.random.random()

0.33408529095323625

# **Generating random no matrices**

In [ ]:
np.random.random((3, 3))

array([[0.79476031, 0.4680844 , 0.09814828],
       [0.088301  , 0.17135968, 0.83808267],
       [0.04532212, 0.07679418, 0.27443978]])

# **Use in if-else**

In [ ]:
rand = np.random.random()
if (rand) > 0.5:
  print("Run the function")
  print(rand)
else:
  print("Don't do anything")
  print(rand)

Run the function
0.5420390742568651


# **arange function -> (start, end, interval)**

In [ ]:
np.arange(2, 11, 2)  # similar to for(i=2; i<11; i+2)

array([ 2,  4,  6,  8, 10])

# **linspace function -> (start, end, no of elements)**
# ****here based upon the no of elements, the interval is equally distributed****

In [ ]:
np.linspace(1, 10, 10)  #ex 1, we want 10 elements b/w 1 to 10

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.linspace(1, 7, 10)   #ex 2, we want 10 elements b/w 1 to 7

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        , 5.66666667, 6.33333333, 7.        ])

# **reshape function -> To change the shape of a predefined array**
# **always try to keep the no of elements as constant like 4x3 to 3x4 or 6x2 means 12 elements are constant...you just cant reshape a 4x3 to 5x3**

In [ ]:
arr = np.random.random((4, 3))   #there's an array of size 4x3
arr

array([[0.02459713, 0.69228914, 0.21665348],
       [0.58871786, 0.40397501, 0.58134546],
       [0.32355206, 0.83831828, 0.15755696],
       [0.84611842, 0.74079061, 0.23635376]])

In [ ]:
arr = np.reshape(arr, (6, 2))   #reshaping the array to 6x2
arr

array([[0.02459713, 0.69228914],
       [0.21665348, 0.58871786],
       [0.40397501, 0.58134546],
       [0.32355206, 0.83831828],
       [0.15755696, 0.84611842],
       [0.74079061, 0.23635376]])

In [ ]:
arr = np.reshape(arr, (3, 4))    #reshaping the array to 3x4
arr

array([[0.02459713, 0.69228914, 0.21665348, 0.58871786],
       [0.40397501, 0.58134546, 0.32355206, 0.83831828],
       [0.15755696, 0.84611842, 0.74079061, 0.23635376]])

# **flatten function -> used to convert a multi dimensional array to single dimensional array, kind of linear array (single row)**

In [ ]:
arr.flatten()  #lastly arr was of 3x4 now it's single dimensional

array([0.02459713, 0.69228914, 0.21665348, 0.58871786, 0.40397501,
       0.58134546, 0.32355206, 0.83831828, 0.15755696, 0.84611842,
       0.74079061, 0.23635376])