# **Importing numpy**

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

# **Adding 1 to every element of the array**

In [ ]:
arr + 1   # can be written as arr += 1 just like C/C++

array([1, 2, 3, 4, 5])

# **Similarly,**

In [ ]:
arr - 1

array([0, 1, 2, 3, 4])

In [ ]:
arr * 2

array([ 2,  4,  6,  8, 10])

In [ ]:
arr / 2

array([0.5, 1. , 1.5, 2. , 2.5])

In [ ]:
arr % 2

array([1, 0, 1, 0, 1])

In [ ]:
arr ** 2  #square of every element

array([ 1,  4,  9, 16, 25])

In [ ]:
arr  #let's print the array once, we've not saved any previous operations into the array so it's unchanged like the initial

array([1, 2, 3, 4, 5])

# **max function**

In [ ]:
arr.max()

5

# **min function**

In [ ]:
arr.min()

1

# **Creating a multi dimensional array**

In [ ]:
arr = np.array([[1, 2, 3],     #defining a list & converting it to numpy array
                [4, 5, 6],
                [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# **max in multidimensional array**

In [ ]:
arr.max(axis = 0)  #when axis=0, it'll give max elements from each col
                   #like in first col, max=7
                   #in second col, max=8
                   #in third col, max=9

array([7, 8, 9])

In [ ]:
arr.max(axis = 1)  #when axis=1, it'll give max elements from each row
                   #like in first row, max=3
                   #in second row, max=6
                   #in third row, max=9

array([3, 6, 9])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# **min in multidimensional array**

In [ ]:
arr.min(axis = 0)  #when axis=0, it'll give min elements from each col
                   #like in first col, min=1
                   #in second col, min=2
                   #in third col, min=3

array([1, 2, 3])

In [ ]:
arr.min(axis = 1)  #when axis=1, it'll give min elements from each row
                   #like in first row, min=1
                   #in second row, min=4
                   #in third row, min=7

array([1, 4, 7])

# **Sum of all elements**

In [ ]:
arr.sum()

45