# **Importing numpy**

In [46]:
import numpy as np

# **Creating two 2 dimensional arrays**

In [47]:
arr1 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
arr2 = np.array([[9, 8, 7],
                [6, 5, 4],
                [3, 2, 1]])

In [ ]:
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

# **Performing addition on same dimensional arrays**

In [ ]:
arr1 + arr2      #both the matrices are (3x3)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

# **Defining another array with different dimension**

In [ ]:
arr3 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

In [ ]:
arr1 + arr3    # (3x3) matrix + (3x4) matrix can't be performed

NameError: name 'arr3' is not defined

# **Same goes for subtraction, multiplication operation**
# **can only be performed b/w same dimensional arrays**

In [49]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

# **Performing multiplication on same dimensional arrays**

In [ ]:
arr1 * arr2

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

# **Performing dot Operation**

In [ ]:
arr1.dot(arr2)      # (1*9) + (2*6) + (3*3) = 30 -> (r1,c1)
                    # (4*9) + (5*6) + (6*3) = 84 -> (r2, c1)
                    # (7*9) + (8*6) + (9*3) = 138 -> (r3, c1)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [ ]:
arr2.dot(arr1)    # arr1.dot(arr2) is not same as arr2.dot(arr1)

array([[ 90, 114, 138],
       [ 54,  69,  84],
       [ 18,  24,  30]])

# **Indexing in array**

In [ ]:
res = np.array([1, 2, 3, 4, 5])  #left to right index -> 0, 1, 2, 3,....
                                 #right to left index -> ..., -3, -2, -1

In [ ]:
print(res[:])       #printing all the elements

print(res[:1])      #prints only the first element

print(res[:3])      #prints from 0th to 2nd index

print(res[2:])      #prints from 2nd index till the end

print(res[:-1])     #prints excepts the last index

print(res[:-2])     #prints except the last 2 indexes

print(res[2:4])     #starting from 2nd index, prints upto 3rd index (always end-1)

[1 2 3 4 5]
[1]
[1 2 3]
[3 4 5]
[1 2 3 4]
[1 2 3]
[3 4]


# **Indexing in multi dimensional array**

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(arr1[:, :])     #first : for row slicing, second : for col slicing. Here it prints all the elements as nothing passed

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(arr1[:, :1])    #only the first col is printed

[[1]
 [4]
 [7]]


In [ ]:
print(arr1[:1, :])   #only the first row is printed

[[1 2 3]]


In [ ]:
print(arr1[:2, :])   #only the first two rows are printed

[[1 2 3]
 [4 5 6]]


In [ ]:
print(arr1[:, 1:2])   #only the middle col is printed

[[2]
 [5]
 [8]]


In [ ]:
print(arr1[1:2, 1:2])   #only the middle row & middle col is printed -> means 5

[[5]]


In [ ]:
print(arr1[1:, 1:])   #only the last two rows and last two cols are printed

[[5 6]
 [8 9]]
