# **Importing numpy**

In [4]:
import numpy as np

# **Creating an one dimensional array**

In [7]:
res = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
res

array([1, 2, 3, 4, 5, 6, 7, 8])

# **Accessing any random element**

In [11]:
print(res[0])
print(res[2])

1
3


# printing all the elements

In [12]:
res[ : ]

array([1, 2, 3, 4, 5, 6, 7, 8])

# **printing starts from 3rd index and goes all the way up to the end**

In [13]:
res[3 : ]

array([4, 5, 6, 7, 8])

# **it always prints one element less than the upper bound mentioned**

In [19]:
res[ : 3]    #prints up to the 2nd index

array([1, 2, 3])

# **printing except the last element**

In [14]:
res[ : -1]

array([1, 2, 3, 4, 5, 6, 7])

# **printing except the last 3 elements**

In [15]:
res[ : -3]

array([1, 2, 3, 4, 5])

# **removing first and last 3 elements**

In [16]:
res[3 : -3]

array([4, 5])

# **Creating a multi dimensional array**

In [5]:
arr= np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [8, 7, 6, 5],
               [4, 3, 2, 1]])

In [6]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

# **printing all the elements, first : for row slicing and second : for col slicing**

In [20]:
arr[ : , : ]

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

# **printing only the first row**

In [21]:
arr[ : 1, : ]

array([[1, 2, 3, 4]])

# **printing only the first col**

In [22]:
arr[ : , : 1]

array([[1],
       [5],
       [8],
       [4]])

# **printing the last two rows**

In [24]:
arr[2 : , : ]

array([[8, 7, 6, 5],
       [4, 3, 2, 1]])

# **printing except the first row and first col (cropping an array)**

In [25]:
arr[1 : , 1 : ]

array([[6, 7, 8],
       [7, 6, 5],
       [3, 2, 1]])

In [26]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

# **accessing 6 of the 3rd row**

In [27]:
arr[2 : 3, 2 : 3]   #sing slicing

array([[6]])

In [28]:
arr[1, 1]   #using indexing (think like the indexes in a matrix)

6

In [29]:
arr[2, 3]

5