# **Importing numpy**

In [ ]:
import numpy as np

# **Creating a multi dimensional numpy array**

In [ ]:
arr = np.array([[7, 3, 8, 6, 4],
                [7, 2, 9, 8, 6],
                [5, 4, 2, 3, 1]])
arr

array([[7, 3, 8, 6, 4],
       [7, 2, 9, 8, 6],
       [5, 4, 2, 3, 1]])

In [ ]:
arr.ndim    #checking dimension

2

# **Sorting using numpy library**

In [ ]:
arr

array([[7, 3, 8, 6, 4],
       [7, 2, 9, 8, 6],
       [5, 4, 2, 3, 1]])

#   **parameters for sorting:**
#   ****1. array name****
#   ****2. axis(if 0 -> col wise sorting, if 1 -> row wise sorting)****
#   ****3. kind(quicksort, mergesort, heapsort, stable)****

In [ ]:
np.sort(arr, axis=1, kind='mergesort')      #row wise sorting using mergesort as axis=1

array([[3, 4, 6, 7, 8],
       [2, 6, 7, 8, 9],
       [1, 2, 3, 4, 5]])

In [ ]:
arr

array([[7, 3, 8, 6, 4],
       [7, 2, 9, 8, 6],
       [5, 4, 2, 3, 1]])

In [ ]:
np.sort(arr, axis=0, kind='mergesort')      #col wise sorting using mergesort as axis=0

array([[5, 2, 2, 3, 1],
       [7, 3, 8, 6, 4],
       [7, 4, 9, 8, 6]])

In [ ]:
np.sort(arr, kind='mergesort')      #if axis is not defined it'll automatically sort as row wise

array([[3, 4, 6, 7, 8],
       [2, 6, 7, 8, 9],
       [1, 2, 3, 4, 5]])