# **Importing numpy**

In [2]:
import numpy as np

# **Creating two 2 dimensional arrays**

In [3]:
arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr2 = np.array([[8, 7, 6, 5], [4, 3, 2, 1]])

In [4]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
arr2

array([[8, 7, 6, 5],
       [4, 3, 2, 1]])

# **For Merging we've hstack & vstack function**

# **vstack -> merges two arrays vertically**

In [6]:
np.vstack((arr1, arr2))    #arr1 will end then arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [7]:
np.vstack((arr2, arr1))   #arr2 will end then arr1

array([[8, 7, 6, 5],
       [4, 3, 2, 1],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

# **hstack -> merges two arrays horizontally**

In [8]:
np.hstack((arr1, arr2))     #from the middle, left portion is arr1 & right portion is arr2

array([[1, 2, 3, 4, 8, 7, 6, 5],
       [5, 6, 7, 8, 4, 3, 2, 1]])

In [9]:
np.hstack((arr2, arr1))     #from the middle, left portion is arr2 & right portion is arr1

array([[8, 7, 6, 5, 1, 2, 3, 4],
       [4, 3, 2, 1, 5, 6, 7, 8]])

# **Merging using concatenate function**

In [10]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
arr2

array([[8, 7, 6, 5],
       [4, 3, 2, 1]])

# ****horizontal or col wise manner concatenation****

In [12]:
np.concatenate((arr1, arr2), axis=0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [13]:
np.concatenate((arr2, arr1), axis=0)

array([[8, 7, 6, 5],
       [4, 3, 2, 1],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

# ****vertical or row wise manner concatenation****

In [14]:
np.concatenate((arr1, arr2), axis=1)

array([[1, 2, 3, 4, 8, 7, 6, 5],
       [5, 6, 7, 8, 4, 3, 2, 1]])

In [15]:
np.concatenate((arr2, arr1), axis=1)

array([[8, 7, 6, 5, 1, 2, 3, 4],
       [4, 3, 2, 1, 5, 6, 7, 8]])

# ****By default the axis is set to 0 means col wise concatenation it'll do****
# ****Also storing the result as a new array for future referencing****

In [18]:
res = np.concatenate((arr1, arr2))
res

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

# **Spliting a numpy array**

# ****vertical or row wise splitting****

In [24]:
np.vsplit(res, 2)     #parameters: 1.name of the array to be splitted, 2.how many parts it'll get splitted here it's 2

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[8, 7, 6, 5],
        [4, 3, 2, 1]])]

In [25]:
np.vsplit(res, 4)     #splitting in 4 equal parts...if we take this as 3 it'll show error bcz of inequal split

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[8, 7, 6, 5]]),
 array([[4, 3, 2, 1]])]

# ****horizontal or col wise splitting****

In [26]:
np.hsplit(res, 2)

[array([[1, 2],
        [5, 6],
        [8, 7],
        [4, 3]]),
 array([[3, 4],
        [7, 8],
        [6, 5],
        [2, 1]])]

In [27]:
np.hsplit(res, 4)

[array([[1],
        [5],
        [8],
        [4]]),
 array([[2],
        [6],
        [7],
        [3]]),
 array([[3],
        [7],
        [6],
        [2]]),
 array([[4],
        [8],
        [5],
        [1]])]