# **Importing numpy**

In [1]:
import numpy as np

# **defining a list**

In [3]:
lst = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# **printing the no of elements as well as the elements inside the list that are greateer than 5**
# **using basic for loop (will implement using numpy later on!)**

In [11]:
count = 0

for i in lst:
  if (i > 5):
    print(i)
    count += 1
print("No of elements that are greater than 5 is: ", count)

6
7
8
9
10
No of elements that are greater than 5 is:  5


# **taking the same list and converting it into numpy array**

In [12]:
lst = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [13]:
lst

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# **calculating length of the numpy array**

In [17]:
len(lst)    #as ther're total 10 elements

10

# **wherever the values are greater than 5, those values are true otherwise false**

In [8]:
lst > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

# **printing only those elements that are > 5 using numpy array**

In [15]:
lst[lst > 5]

array([ 6,  7,  8,  9, 10])

# **calculating the no of elements that are greater than 5**

In [16]:
len(lst[lst > 5])

5

# **printing the elements that are divisible by 3**

In [19]:
lst[lst % 3 == 0]

array([3, 6, 9])

# **calculating the no of elements that are divisible by 3**

In [20]:
len(lst[lst % 3 == 0])

3

# **we implemented the greater than 5 case using list (for loop) and also using numpy arrays. But as compared to list, numpy array operations are much faster than lists and also the lines of code are much lesser as compared to list. No need to use any loops!**