In [15]:
import numpy as np
import pandas as pd

In [28]:
df = pd.read_csv('BlackFriday.csv')

In [29]:
df

User_ID Product_ID Gender    Age  Occupation City_Category  \
0       1000001  P00069042      F   0-17          10             A   
1       1000001  P00248942      F   0-17          10             A   
2       1000001  P00087842      F   0-17          10             A   
3       1000001  P00085442      F   0-17          10             A   
4       1000002  P00285442      M    55+          16             C   
...         ...        ...    ...    ...         ...           ...   
537572  1004737  P00193542      M  36-45          16             C   
537573  1004737  P00111142      M  36-45          16             C   
537574  1004737  P00345942      M  36-45          16             C   
537575  1004737  P00285842      M  36-45          16             C   
537576  1004737  P00118242      M  36-45          16             C   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                               2               0                   3   
1                               2               0                   1   
2                               2               0                  12   
3                               2               0                  12   
4                              4+               0                   8   
...                           ...             ...                 ...   
537572                          1               0                   1   
537573                          1               0                   1   
537574                          1               0                   8   
537575                          1               0                   5   
537576                          1               0                   5   

        Product_Category_2  Product_Category_3  Purchase  
0                      NaN                 NaN      8370  
1                      6.0                14.0     15200  
2                      NaN                 NaN      1422  
3                     14.0                 NaN      1057  
4                      NaN                 NaN      7969  
...                    ...                 ...       ...  
537572                 2.0                 NaN     11664  
537573                15.0                16.0     19196  
537574                15.0                 NaN      8043  
537575                 NaN                 NaN      7172  
537576                 8.0                 NaN      6875  

[537577 rows x 12 columns]

In [30]:
df.isnull().sum()

User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2            166986
Product_Category_3            373299
Purchase                           0
dtype: int64

In [31]:
del df['Product_Category_2']
del df['Product_Category_3']

In [33]:
df.isnull().sum()

User_ID                       0
Product_ID                    0
Gender                        0
Age                           0
Occupation                    0
City_Category                 0
Stay_In_Current_City_Years    0
Marital_Status                0
Product_Category_1            0
Purchase                      0
dtype: int64

In [34]:
df.head()

User_ID Product_ID Gender   Age  Occupation City_Category  \
0  1000001  P00069042      F  0-17          10             A   
1  1000001  P00248942      F  0-17          10             A   
2  1000001  P00087842      F  0-17          10             A   
3  1000001  P00085442      F  0-17          10             A   
4  1000002  P00285442      M   55+          16             C   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  Purchase  
0                          2               0                   3      8370  
1                          2               0                   1     15200  
2                          2               0                  12      1422  
3                          2               0                  12      1057  
4                         4+               0                   8      7969

# **Q1. How many no of unique users are there in the dataset?**

In [39]:
df['User_ID'].nunique()   # tells the total no of unique user IDs

5891

# **Q2. Names of all the unique users are there in the dataset?**

In [36]:
df['User_ID'].unique()    # creates an numpy array and storing all the unique user IDs

array([1000001, 1000002, 1000003, ..., 1004113, 1005391, 1001529])

# **Q3. How many no of unique products are there in the dataset?**

In [41]:
df['Product_ID'].nunique()    # tells the total no of unique product IDs

3623

# **Q4. Name of all the unique products are there in the dataset?**

In [40]:
df['Product_ID'].unique()    # creates an numpy array and storing all the unique product IDs

array(['P00069042', 'P00248942', 'P00087842', ..., 'P00038842',
       'P00295642', 'P00091742'], dtype=object)

# **Q5. How many gender types are there in the dataset?**

In [44]:
df['Gender'].unique()

array(['F', 'M'], dtype=object)

# **Q6. How many age groups are there in the dataset?**

In [42]:
df['Age'].unique()

array(['0-17', '55+', '26-35', '46-50', '51-55', '36-45', '18-25'],
      dtype=object)

# **Q7. How many different occupations are there in the dataset?**

In [45]:
df['Occupation'].unique()

array([10, 16, 15,  7, 20,  9,  1, 12, 17,  0,  3,  4, 11,  8, 19,  2, 18,
        5, 14, 13,  6])

In [46]:
df['Occupation'].nunique()

21

# **Q8. How many different cities are there in the dataset?**

In [47]:
df['City_Category'].unique()

array(['A', 'C', 'B'], dtype=object)

# **Q9. How many different values of stay in current city are there in the dataset?**

In [48]:
df['Stay_In_Current_City_Years'].unique()

array(['2', '4+', '3', '1', '0'], dtype=object)

# **Q10. How many different marital statuses are there in the dataset?**

In [49]:
df['Marital_Status'].unique()

array([0, 1])

# **Q11. How many different values of product category 1 are there in the dataset?**

In [50]:
df['Product_Category_1'].unique()

array([ 3,  1, 12,  8,  5,  4,  2,  6, 14, 11, 13, 15,  7, 16, 18, 10, 17,
        9])

In [51]:
df['Product_Category_1'].nunique()

18

# **Q13. How many different values of purchases are there in the dataset?**

In [52]:
df['Purchase'].unique()

array([ 8370, 15200,  1422, ..., 14539, 11120, 18426])

In [53]:
df['Purchase'].nunique()

17959

# **Q14. Sum of all the purchase made by all the users in total?**

In [54]:
df['Purchase'].sum()

5017668378

# **Q15. Mean of purchase column?**

In [55]:
import statistics as st

In [56]:
st.mean(df['Purchase'])

9333.859852635065

# **Finding all the unique values for each of the column using a single for loop (automation)**

In [57]:
for i in df.columns:
  print(i, df[i].nunique())

User_ID 5891
Product_ID 3623
Gender 2
Age 7
Occupation 21
City_Category 3
Stay_In_Current_City_Years 5
Marital_Status 2
Product_Category_1 18
Purchase 17959
